name: Nix Build
on:
  pull_request:
  push:
    branches-ignore:
      - master

jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v24
        with:
          extra_nix_config: |
            accept-flake-config = true

      - run: nix build
