name: Update Nix Cache
on:
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v24
        with:
          extra_nix_config: |
            accept-flake-config = true
      - uses: cachix/cachix-action@v12
        with:
          name: sohi
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipAddingSubstituter: true
      - run: nix build
